version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    labels:
      - 'dependencies'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
      time: '02:34'
    commit-message:
      include: 'scope'
      prefix: 'chore'
    allow:
      - dependency-type: 'development'
    cooldown:
      default-days: 3
    groups:
      dev-dependencies:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
